baseurl = "https://developers.livechatinc.com/docs"
languageCode = "en-us"
title = "LiveChat API Docs"
disableHugoGeneratorInject = true

pygmentsCodeFences = true
pygmentsUseClassic = true
pygmentsUseClasses = true